name: 'Publish JSR'
description: |
  This workflow serializes the build binary to Base64 and generates a JSON file with meta data about the file.
  The file then gets published to JSR (@serial/cpp-bindings-linux).

on:
  workflow_call:
    inputs:
      publish:
        description: 'Whether to actually publish'
        required: true
        type: boolean

      version:
        description: 'Package version'
        required: true
        type: string

      artifact-name:
        description: 'Name of the artifact'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  publish-jsr:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Deno'
        uses: denoland/setup-deno@v2
        with:
          deno-version: '2.x'
      
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: 'artifacts'

      - name: 'Prepare files for JSR'
        run: |
          ./jsr/scripts/copy_binary.sh \
            ./artifacts/libcpp_bindings_linux.so \
            ./jsr/bin/x86_64.so

          ./jsr/scripts/binary_to_json.sh \
            ./artifacts/libcpp_bindings_linux.so \
            ./jsr/bin/x86_64.json \
            linux-x86_64

          ./jsr/scripts/set_version.sh \
            jsr/jsr.json \
            "${{ inputs.version }}"
      
      - name: 'Publish package to JSR (normal)'
        if: inputs.publish
        working-directory: jsr
        run: |
          deno publish --allow-dirty

      - name: 'Publish package to JSR (dry-run)'
        if: ${{ !inputs.publish }}
        working-directory: jsr
        run: |
          deno publish --allow-dirty --dry-run

